# Exercise 1.A NumPy: Manipulating Arrays

This exercise explores looping through arrays, joining and stacking arrays, splitting arrays, and searching/filtering values using NumPy.


In [1]:
import numpy as np


## Looping Through Arrays


In [2]:
arrA = np.array([
    [11, 12, 13],
    [14, 15, 16]
])

print(arrA)


[[11 12 13]
 [14 15 16]]


In [3]:
for x in arrA:
    print(x * 2)


[22 24 26]
[28 30 32]


In [4]:
for x in arrA:
    for y in x:
        print(y * 2)


22
24
26
28
30
32


The first loop prints each *row* multiplied by 2, so the output is in 2D chunks.
The second loop prints each *individual element* multiplied by 2, so the output is 1D values printed one at a time.


In [5]:
for x in arrA:
    loop_result = x * 2
    print(loop_result)

# Comment:
# This prints each entire row multiplied by 2 at once because x is the whole row,
# not a single element. That's why the output is grouped in arrays instead of single numbers.


[22 24 26]
[28 30 32]


## Joining and Stacking Arrays


In [6]:
joined_array_1 = np.concatenate((arrA, arrA), axis=0)
print(joined_array_1)


[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [7]:
joined_array_2 = np.concatenate((arrA, arrA), axis=1)
print(joined_array_2)


[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [8]:
stacked_array_1 = np.stack((joined_array_1, joined_array_1))
print(stacked_array_1)


[[[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]

 [[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]]


In [9]:
# This will cause an error because joined_array_1 and joined_array_2
# do NOT have the same shape.
stacked_array_2 = np.stack((joined_array_1, joined_array_2))
print(stacked_array_2)

# Comment:
# The error says the input arrays must have the same shape.
# joined_array_1 and joined_array_2 have different dimensions, so stacking fails.


ValueError: all input arrays must have the same shape

In [ ]:
another_joined_array = np.concatenate((joined_array_1, arrA), axis=0)
print(another_joined_array)


In [ ]:
another_2 = np.concatenate((joined_array_1, arrA), axis=1)
print(another_2)

# Comment:
# Error: the arrays cannot be concatenated along axis=1 because their row lengths differ.
# NumPy requires matching dimensions along all other axes.


In [ ]:
h = np.hstack((arrA, arrA))
print(h)
# hstack places arrays side-by-side (horizontal stacking).

v = np.vstack((arrA, arrA))
print(v)
# vstack places arrays on top of each other (vertical stacking).

d = np.dstack((arrA, arrA))
print(d)
# dstack stacks arrays along a new 3rd dimension.


## Splitting Arrays


In [ ]:
splitsky = np.array_split(joined_array_1, 2)
print(splitsky)

# Comment:
# Result: 2 arrays, each 2D, each containing half of joined_array_1.


In [ ]:
spliterino = np.array_split(joined_array_1, 3)
print(spliterino)

# Comment:
# Result: 3 arrays. NumPy splits as evenly as possible.
# Some arrays may have different row counts.


## Searching and Replacing Array Values


In [ ]:
result_1 = np.where(arrA % 2 == 0, arrA, 'odd')
print(result_1)


## Sorting and Filtering Arrays


In [ ]:
arrB = np.array([
    [7, 6],
    [13, 5],
    [7, 3]
])

arrB_sorted = np.sort(arrB)
print(arrB_sorted)


In [ ]:
print(arrB)

z = arrB < 7
arrC = arrB[z]
print(arrC)


In [ ]:
y = arrB >= 7
arrD = arrB[y]
print(arrD)
