# Exercise 1.B NumPy Random

This exercise explores generating random numbers, random selections, weighted choices, and normal distributions using NumPy.


In [1]:
import numpy as np


## Generating Random Numbers


In [2]:
r_1 = np.random.randint(1, 21, size=2)
print(r_1)


[11 18]


In [3]:
r_2 = np.random.randint(1, 21, size=(1, 2))
print(r_2)


[[13 15]]


In [4]:
r_3 = np.random.rand(2, 1)
print(r_3)


[[0.35834782]
 [0.11698891]]


In [5]:
r_4 = np.random.randint(20, 101, size=(4, 5))
print(r_4)


[[ 42 100  74  31  20]
 [ 88  44  53  33  52]
 [ 67  81  52  40  59]
 [100  22  41  79  76]]


In [6]:
r_5 = np.random.rand(4, 5)
print(r_5)


[[0.10483207 0.95286725 0.59974347 0.30255079 0.12411186]
 [0.61329876 0.61937367 0.44371555 0.71892338 0.19893018]
 [0.34799655 0.01130271 0.05278234 0.11653033 0.585407  ]
 [0.16133626 0.8486524  0.87976682 0.32061161 0.91341339]]


## Generating Random Choices from an Array


In [7]:
students = np.array([
    "Ava", "Ben", "Carlos", "Diana",
    "Eli", "Fatima", "Grace", "Hector",
    "Ivy", "Jamal", "Kara", "Liam"
])
students


array(['Ava', 'Ben', 'Carlos', 'Diana', 'Eli', 'Fatima', 'Grace',
       'Hector', 'Ivy', 'Jamal', 'Kara', 'Liam'], dtype='<U6')

In [8]:
call_on = np.random.choice(students)
print(call_on)


Grace


In [9]:
breakout_groups = np.random.choice(students, size=(3, 4), replace=False)
print(breakout_groups)

# Comment:
# This is NOT an effective way to assign breakout groups because the sampling is random
# and does not guarantee balanced groups or prevent repeating the same groupings each run.


[['Ava' 'Liam' 'Eli' 'Kara']
 ['Diana' 'Grace' 'Carlos' 'Ben']
 ['Ivy' 'Hector' 'Fatima' 'Jamal']]


In [10]:
# Example probability distribution (must sum to 1)
p_values = [
    0.00,  # Ava (never selected)
    0.05,  # Ben
    0.10,  # Carlos
    0.05,  # Diana
    0.10,  # Eli
    0.30,  # Fatima (30% chance)
    0.10,  # Grace
    0.10,  # Hector
    0.05,  # Ivy
    0.05,  # Jamal
    0.05,  # Kara
    0.05   # Liam
]

call_on_weighted = np.random.choice(students, size=5, p=p_values)
print(call_on_weighted)

# Comment:
# Fatima has the highest chance (30%).
# Ava has 0% chance and will never be selected.
# Other students have smaller but non-zero probabilities.


['Fatima' 'Fatima' 'Grace' 'Fatima' 'Jamal']


## Generating a Normal Distribution


In [11]:
bell_curve = np.random.normal(loc=10, scale=5, size=(4, 5))
print(bell_curve)


[[14.81275697  7.46362942  5.99868034 10.82826025 15.34722641]
 [ 6.80457095  8.61896362  6.37533569 14.31922392  9.39617604]
 [16.51668918 13.4052812  16.69249804  3.4851428   3.38026198]
 [ 3.88785088 12.23962379  8.1840444   6.98563713 16.26212515]]
