# Exercise 1.C Performing operations on arrays

In this exercise, I’m putting NumPy to work — shuffling, adding, rounding, and doing all the math magic. Let’s get into it.


In [ ]:
import numpy as np


## Sample Arrays

These are the same random arrays I created in Exercise 1.B — bringing them back like a rebooted TV show.


In [ ]:
r_1 = np.random.randint(1, 10, (2, 3))
r_2 = np.random.randint(5, 20, (2, 3))
r_3 = np.random.normal(10, 5, (4, 5))
r_4 = np.random.randint(1, 50, (2, 5))
r_5 = np.random.random((3, 3))


## Permutations


In [ ]:
print("Original r_4:")
print(r_4)


Original r_4:
[[30  6 32 25 20]
 [13  5  9 30 36]]


In [ ]:
np.random.shuffle(r_4)
print("Shuffled r_4:")
print(r_4)


Shuffled r_4:
[[30  6 32 25 20]
 [13  5  9 30 36]]


Shuffling modifies the array *in place*. NumPy rearranged the rows of r_4, but did not return a new array. It’s like shuffling a deck — the deck itself changes.


In [ ]:
new_shuffle = np.random.permutation(r_4)
print("Permutation result:")
print(new_shuffle)

print("r_4 after permutation (unchanged):")
print(r_4)


Permutation result:
[[30  6 32 25 20]
 [13  5  9 30 36]]
r_4 after permutation (unchanged):
[[30  6 32 25 20]
 [13  5  9 30 36]]


Shuffle changes the original array directly — like rearranging furniture in your room.

Permutation returns a *new* rearranged array and leaves the original untouched — like taking a picture of your room and rearranging the picture instead.


## Mathematical Operations


In [ ]:
print("r_1:\n", r_1)
print("shape:", r_1.shape)

print("r_2:\n", r_2)
print("shape:", r_2.shape)

result = np.add(r_1, r_2)
print("r_1 + r_2:\n", result)
print("shape:", result.shape)


r_1:
 [[4 4 2]
 [7 8 7]]
shape: (2, 3)
r_2:
 [[ 7  5  5]
 [19 14 16]]
shape: (2, 3)
r_1 + r_2:
 [[11  9  7]
 [26 22 23]]
shape: (2, 3)


In [ ]:
print("r_1 shape:", r_1.shape)
print("r_3 shape:", r_3.shape)

result = np.add(r_1, r_3)
print(result)
print("shape:", result.shape)

# COMMENT:
# This error is expected. r_1 has shape (2,3) and r_3 has shape (4,5).
# These shapes are NOT compatible for broadcasting because:
# - None of the dimensions match
# - Neither dimension is 1 (so NumPy cannot stretch either array)
# Because of this, NumPy cannot align the arrays, so it raises a ValueError.


r_1 shape: (2, 3)
r_3 shape: (4, 5)


ValueError: operands could not be broadcast together with shapes (2,3) (4,5) 

In [ ]:
print("r_2 shape:", r_2.shape)
print("r_4 shape:", r_4.shape)

result = np.add(r_2, r_4)
print(result)
print("shape:", result.shape)


In [ ]:
# r_1 + r_4
try:
    print(np.add(r_1, r_4))
except Exception as e:
    print("Error for r_1 + r_4:", e)

# r_2 + r_4
try:
    print(np.add(r_2, r_4))
except Exception as e:
    print("Error for r_2 + r_4:", e)

# r_3 + r_4
try:
    print(np.add(r_3, r_4))
except Exception as e:
    print("Error for r_3 + r_4:", e)

# Comment:
# These errors happen because the shapes are not compatible for broadcasting.


In [ ]:
print(r_4 + np.array([1]))
print(r_4 + np.array([[1]]))
print(r_4 + np.array([1,1,1,1,1]))

try:
    print(r_4 + np.array([[1],[1]]))
except Exception as e:
    print("Error:", e)


Broadcasting works when NumPy can stretch one array to match the shape of another.

Using add(), each element of the smaller array gets added to the matching position in the larger array. NumPy compares shapes from right to left — if a dimension is 1 or matches, it can broadcast. The resulting array always takes the larger shape.


## Rounding


In [ ]:
print(r_3)


In [ ]:
print(np.trunc(r_3))


In [ ]:
print(np.fix(r_3))


In [ ]:
print(np.floor(r_3))


In [ ]:
print(np.ceil(r_3))


In [ ]:
print(np.round(r_3, 2))


## Cumulative Operations


In [ ]:
print(r_4)


In [ ]:
print(np.sum(r_4))


In [ ]:
print(np.sum(r_4, axis=0))


In [ ]:
print(np.sum(r_4, axis=1))


In [ ]:
print(np.cumsum(r_4))


In [ ]:
print(np.cumsum(r_4, axis=0))


## Grocery Problem


In [ ]:
bag1 = np.array([2, 3, 4, 0])
bag2 = np.array([4, 0, 1, 2])

print(bag1)
print(bag2)


In [ ]:
total1 = np.sum(bag1)
total2 = np.sum(bag2)

print(f"The first bag contains {total1} items, and the second bag contains {total2} items.")


In [ ]:
combined = bag1 + bag2
print(f"There are {combined[0]} vegetables, {combined[1]} fruits, {combined[2]} boxes of snacks, and {combined[3]} beverages in the two grocery bags.")


## Teamwork


In [ ]:
ali = np.array([5, 4, 6, 4, 2])


In [ ]:
ben = np.array([0, 5, 5, 3, 4])


In [ ]:
all_knocks = np.array([ali, ben, carla])
print(all_knocks)


In [ ]:
print("Ali total:", np.sum(ali))
print("Ben total:", np.sum(ben))
print("Carla total:", np.sum(carla))

print("Group total:", np.sum(all_knocks))


In [ ]:
daily_total = np.sum(all_knocks, axis=0)
rolling = np.cumsum(daily_total)
estimated_votes = rolling * 0.5

print("Estimated rolling votes by day:")
print(estimated_votes)
