# Ex5A – NumPy Fundamentals

This exercise introduces basic NumPy concepts including creating arrays, checking data types, slicing, transposing, and working with multi‑dimensional arrays.


In [16]:
import numpy as np


## Array Basics
Below are examples of creating Python lists and converting them into NumPy arrays.


In [17]:
fruits = ["apple", "banana", "cherry", "date"]
fruits


['apple', 'banana', 'cherry', 'date']

In [18]:
arr_1 = np.array(fruits)
print(arr_1)


['apple' 'banana' 'cherry' 'date']


In [19]:
arr_1.dtype


dtype('<U6')

The dtype tells us the data type stored in the array.
For example, dtype('<U6') means:
- U = Unicode string
- 6 = maximum length of the strings in the array


In [20]:
arr_2 = np.array([
    [10, 11, 12],
    [13, 14, 15]
])

print(arr_2)


[[10 11 12]
 [13 14 15]]


In [21]:
print(arr_2.T)


[[10 13]
 [11 14]
 [12 15]]


Using arr_2.T does NOT change the original array.
It only returns a transposed *view* of the data.
arr_2 itself stays the same.


In [22]:
arr_3 = np.array([
    [1, 3, 5],
    [2, 4, 6]
])

print(arr_3)


[[1 3 5]
 [2 4 6]]


In [23]:
arr_4 = np.array([arr_3[0, 2], arr_3[1, 1]])
print(arr_4)


[5 4]


In [24]:
arr_5 = np.ones((2, 2, 2))
print(arr_5)


[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
